services:
#    file.example:
#        class: FileBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    EntityServices:
# The namespace with the name of the class that contain our service
        class: FileBundle\Service\Entity
#The services that we will inject (see the constructor)
        arguments: [ '@doctrine.orm.entity_manager' ,'@service_container' ]

imports:
    - { resource: parameters.yml }
